<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Teacher_icon fa fa-times pl-2 mr-0</name>
   <tag></tag>
   <elementGuidId>af119c59-7f2d-4760-af3c-a2cecdb3bd2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form_autocomplete_selection-1641923549994']/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-times.pl-2.mr-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-times pl-2 mr-0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_autocomplete_selection-1641923549994&quot;)/span[@class=&quot;badge badge-secondary clickable text-wrap text-break line-height-4 m-1&quot;]/i[@class=&quot;icon fa fa-times pl-2 mr-0&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_autocomplete_selection-1641923549994']/span/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/div[2]/span/i</value>
   </webElementXpaths>
</WebElementEntity>
